images:
- name: gardener-extension-provider-mock
  sourceRepository: github.com/gardener/gardener-extensions/tree/master/controllers/provider-mock
  repository: timebertsap/gardener-extension-provider-mock
  tag: "0.1.0"
